plugins:
  api_sports_enabled:
    default: true
    client: true
    type: bool

  api_sports_api_key:
    default: ""
    client: true
    type: string
    secret: false

  api_sports_theme:
    default: "dark"
    client: true
    type: enum
    choices:
      - dark
      - light
      - grey
      - blue

  api_sports_sevilla_team_id:
    default: "536"
    client: true
    type: string

  api_sports_laliga_league_id:
    default: "140"
    client: true
    type: string

  api_sports_season:
    default: "2025"
    client: true
    type: string

  api_sports_widget_refresh:
    default: 60
    client: true
    type: integer
    min: 15
    max: 3600
